services: # containers. same as docker run
  prometheus: # the service name. this is also DNS name inside network
    image: prom/prometheus # Optional if you use build: .It will go to dockerhub and download the latest prom/prometheus image if not present locally
    container_name: prometheus # what we see when we do docker ps. usually good to be the same as the service name above
    command:
      - '--config.file=/etc/prometheus/prometheus.yml' # Optional, replace the default CMD specified by the image. here we use it because we also load a configuration file
    ports: #same as -p in docker run
      - 9090:9090
    restart: unless-stopped # Optional. Options: no, on-failure, always, unless-stopped (in what case to restart the container)
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment: # Optional, same as -e in docker run
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
volumes: # Same as -v in docker run
  prom_data: